"""Rename Checkpoint to Milestone

Revision ID: 7a0a6b11da4b
Revises: 97486abb0245
Create Date: 2024-11-07 00:24:36.231161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0a6b11da4b'
down_revision = '97486abb0245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_date', sa.DATETIME(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
