"""Add full name and location to User Model

Revision ID: 97486abb0245
Revises: f0f378b66497
Create Date: 2024-11-06 23:56:10.794635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97486abb0245'
down_revision = 'f0f378b66497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
